export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";

export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";

export const CURRENT_USER_REQUEST = "CURRENT_USER_REQUEST";
export const CURRENT_USER_SUCCESS = "CURRENT_USER_SUCCESS";
export const CURRENT_USER_ERROR = "CURRENT_USER_ERROR";

export const FETCH_PROPERTIES_REQUEST = "FETCH_PROPERTIES_REQUEST";
export const FETCH_PROPERTIES_SUCCESS = "FETCH_PROPERTIES_SUCCESS";
export const FETCH_PROPERTIES_ERROR = "FETCH_PROPERTIES_ERROR";

export const FETCH_PROPERTY_BY_ID_REQUEST = "FETCH_PROPERTY_BY_ID_REQUEST";
export const FETCH_PROPERTY_BY_ID_SUCCESS = "FETCH_PROPERTY_BY_ID_SUCCESS";
export const FETCH_PROPERTY_BY_ID_ERROR = "FETCH_PROPERTY_BY_ID_ERROR";

export const ADD_NEW_PROPERTY_REQUEST = "ADD_NEW_PROPERTY_REQUEST";
export const ADD_NEW_PROPERTY_SUCCESS = "ADD_NEW_PROPERTY_SUCCESS";
export const ADD_NEW_PROPERTY_ERROR = "ADD_NEW_PROPERTY_ERROR";

export const UPDATE_PROPERTY_REQUEST = "UPDATE_PROPERTY_REQUEST";
export const UPDATE_PROPERTY_SUCCESS = "UPDATE_PROPERTY_SUCCESS";
export const UPDATE_PROPERTY_ERROR = "UPDATE_PROPERTY_ERROR";

export const DELETE_PROPERTY_REQUEST = "DELETE_PROPERTY_REQUEST";
export const DELETE_PROPERTY_SUCCESS = "DELETE_PROPERTY_SUCCESS";
export const DELETE_PROPERTY_ERROR = "DELETE_PROPERTY_ERROR";

export const FILTER_PROPERTIES_REQUEST = "FILTER_PROPERTIES_REQUEST";
export const FILTER_PROPERTIES_SUCCESS = "FILTER_PROPERTIES_SUCCESS";
export const FILTER_PROPERTIES_ERROR = "FILTER_PROPERTIES_ERROR";

export const ADD_ITEM_TO_FAVOURITES_REQUEST = "ADD_ITEM_TO_FAVOURITES_REQUEST";
export const ADD_ITEM_TO_FAVOURITES_SUCCESS = "ADD_ITEM_TO_FAVOURITES_SUCCESS";
export const ADD_ITEM_TO_FAVOURITES_ERROR = "ADD_ITEM_TO_FAVOURITES_ERROR";

export const FAVOURITE_PROPERTIES_REQUEST = "FAVOURITE_PROPERTIES_REQUEST";
export const FAVOURITE_PROPERTIES_SUCCESS = "FAVOURITE_PROPERTIES_SUCCESS";
export const FAVOURITE_PROPERTIES_ERROR = "FAVOURITE_PROPERTIES_ERROR";

export const DELETE_ITEMS_FROM_FAVOURITES_REQUEST =
  "DELETE_ITEMS_FROM_FAVOURITES_REQUEST";
export const DELETE_ITEMS_FROM_FAVOURITES_SUCCESS =
  "DELETE_ITEMS_FROM_FAVOURITES_SUCCESS";
export const DELETE_ITEMS_FROM_FAVOURITES_ERROR =
  "DELETE_ITEMS_FROM_FAVOURITES_ERROR";

export const UPDATE_PROPERTIES_DELETE = "UPDATE_PROPERTIES_DELETEs";
export const UPDATE_FAV_PROPERTIES = "UPDATE_FAV_PROPERTIES";
export const UPDATE_FAV_LIST = "UPDATE_FAV_LIST";
